@startuml
title Sequence Diagram - Proses Pencatatan Data Bayi

actor Petugas
boundary "Form Data Bayi" as Form
control "BayiController" as Controller
entity "Database" as DB

Petugas -> Form: Buka halaman Data Bayi
Form -> Petugas: Tampilkan form input
Petugas -> Form: Isi data bayi dan klik Simpan
Form -> Controller: Kirim data bayi
Controller -> DB: Simpan data ke tabel bayi
DB --> Controller: Konfirmasi penyimpanan
Controller --> Form: Kirim status berhasil
Form --> Petugas: Tampilkan notifikasi sukses
@enduml


@startuml
title Sequence Diagram - Proses Pengukuran Bayi

actor Petugas
boundary "Form Pengukuran" as Form
control "PengukuranController" as Controller
entity "Database" as DB

Petugas -> Form: Buka menu Pengukuran
Form -> Petugas: Tampilkan daftar bayi
Petugas -> Form: Pilih bayi dan isi data pengukuran
Form -> Controller: Kirim data pengukuran
Controller -> DB: Simpan ke tabel pengukuran
DB --> Controller: Konfirmasi penyimpanan
Controller --> Form: Kirim pesan sukses
Form --> Petugas: Menampilkan hasil penyimpanan
@enduml


@startuml
title Sequence Diagram - Proses Pencatatan Imunisasi

actor Petugas
boundary "Form Imunisasi" as Form
control "ImunisasiController" as Controller
entity "Database" as DB

Petugas -> Form: Buka menu Imunisasi
Form -> Petugas: Tampilkan daftar bayi
Petugas -> Form: Pilih bayi dan isi data imunisasi
Form -> Controller: Kirim data imunisasi
Controller -> DB: Simpan ke tabel imunisasi
DB --> Controller: Konfirmasi sukses
Controller --> Form: Kirim pesan berhasil
Form --> Petugas: Tampilkan notifikasi berhasil
@enduml
 